base_dir: /data/group_data/cx_group/

# data preprocessing
train_dataset_name: fineweb
reference_dataset_name: lambada

## data selection
method: random
gumbel_temp: 0.5
select_from_size: 1024000
selection_size: 102400

## training and evaluation
model_class: pythia
train_config: configs/train_pretrain_decay_pythia-1b.yaml

