method: EKFAC
# Supported methods: Grad_Dot, Grad_Sim, LESS, DataInf, EKFAC

task: "Counterfact"
subset: "Pythia-1b"
# Supported task: Counterfactual, ftrace
# Supported subset: Pythia-1b, Llama-3.2-1B, Llama-3.1-8B

base_model_path: "EleutherAI/pythia-1b"
# Supported model: Pythia-1b, Llama-3.2-1B, Llama-3.1-8B
checkpoint: "DataAttributionEval/Pythia-1b-counterfactual"

device: "cuda"

##################################
# hyperparameter used for DataInf
# regularization: regularization term added to hessian
# fim_estimate_data_ratio: ratio of full training data used to estimate hessian
regularization: 1e-5
fim_estimate_data_ratio: 1.0
##################################

##################################
# hyperparameter used for EKFAC
# regularization: regularization term added to hessian
damping: 1e-7
##################################

##################################
# hyperparameter used for LESS
# proj_dim: projection dimension of gradients
proj_dim: 8192
##################################

save_path: ./