
# data preprocessing
# input:
train_dataset_name: tulu3

## data selection
# input:
# train_data_dir
method: random
select_from_size: 200000
selection_size: 10000

## training
# input:
# selected_train_data_dir
model_class: pythia
train_config: configs/train_finetune_pythia-1b.yaml
train_data_path: /data/hf_cache/datasets/lsds_data/data/training_data/training_data/tulu_3_v3.9_unfiltered.jsonl
checkpoint_dir: "/data/group_data/cx_group/date-models/pythia-1b"
# out_dir: /data/group_data/cx_group/date-models
out_dir: /data/user_data/emilyx/finetune/test2
exp_name: test

# evaluate
eval_tasks: mmlu,gsm8k,bbh,mathqa,sciq,arc_easy,arc_challenge,logiqa,boolq,hellaswag,piqa,winogrande,openbookqa
num_fewshot: 0
batch_size: 16