base_dir: /data/group_data/cx_group/ # /data/user_data/emilyx

# data preprocessing
# input:
train_dataset_name: fineweb
train_data_split: 0
reference_dataset_name: lambada
# output:
train_data_dir: /data/group_data/cx_group/data/fineweb/train/0
val_data_dir: /data/group_data/cx_group/data/fineweb/val/0
reference_data_dir: /data/user_data/emilyx/lambada_openai/train-1024.pt

## data selection
# input:
# train_data_dir
method: gradsim
select_from_size: 1024000
selection_size: 102400
metrics_dir: /data/group_data/cx_group/out/pythia-1b/fineweb/sample-350BT/random/step-00010000/less_full
# output:
selected_train_data_dir: /data/group_data/cx_group/data/fineweb/train/0/gradsim_lambada_pythia1b_step10000

## training
# input:
# selected_train_data_dir
model_class: pythia
train_config: configs/train_pretrain_decay_pythia-1b.yaml

