base_dir: /data/group_data/cx_group/

# data preprocessing
# input:
train_dataset_name: fineweb
train_data_split: 0
reference_dataset_name: lambada_openai
# output:
train_data_dir: /data/group_data/cx_group/data/fineweb/train/0
val_data_dir: /data/group_data/cx_group/data/fineweb/val/0
reference_data_dir: /data/group_data/cx_group/data/lambada_openai/train/train-1024.pt

## data selection
# input:
# train_data_dir
method: edu
select_from_size: 1024000
selection_size: 102400
decoded_train_dir: /data/group_data/cx_group/data/fineweb/train/0/decoded

# output:
selected_train_data_dir: /data/group_data/cx_group/data/fineweb/train/0/edu

## training
# input:
# selected_train_data_dir
model_class: pythia
train_config: configs/train_pretrain_decay_pythia-1b.yaml
